name: test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        go: ["1.16", "1.17", "1.18", "1.19"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: actions/setup-go@be3c94b385c4f180051c996d336f57a34c397495 # v3
        with:
          go-version: ${{ matrix.go }}

      - run: go generate ./...
      - run: git diff --cached --exit-code
      - run: go test ./... -v -cover -coverprofile coverage.out
      - run: go test -bench . -benchmem

      - uses: codecov/codecov-action@f32b3a3741e1053eb607407145bc9619351dc93b # v2
